/// <reference types="node" />
import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { compileToTex } from '../index';
import type { TexOptions, TexSkip } from '../index';

function tex(src: string, opts: TexOptions = {}): string {
  const r = compileToTex(src, opts);
  if (!r.success) throw new Error(`compile failed: ${r.errors[0]?.message}`);
  return r.tex;
}

function skipped(src: string): TexSkip[] {
  const r = compileToTex(src);
  if (!r.success) throw new Error(`compile failed: ${r.errors[0]?.message}`);
  return r.skipped;
}

/** the plot lines only, with the leading indent removed */
function plots(src: string, opts: TexOptions = {}): string[] {
  return tex(src, opts)
    .split('\n')
    .filter(l => l.trim().startsWith('\\addplot') || l.trim().startsWith('\\node'))
    .map(l => l.trim());
}

describe('document shape', () => {
  test('is a standalone pgfplots figure', () => {
    const out = tex('point p = (1, 2)');
    assert.match(out, /\\documentclass\[tikz,border=4pt\]\{standalone\}/);
    assert.match(out, /\\usepackage\{pgfplots\}/);
    assert.match(out, /\\begin\{axis\}\[/);
    assert.match(out, /\\end\{document\}/);
  });

  test('every begin has its end', () => {
    const out = tex('point p = (1, 2)');
    for (const env of ['document', 'tikzpicture', 'axis']) {
      assert.equal(out.split(`\\begin{${env}}`).length, 2, env);
      assert.equal(out.split(`\\end{${env}}`).length, 2, env);
    }
  });

  test('the viewport reaches the axis', () => {
    const out = tex('point p = (1, 2)', { viewport: { xmin: -2, xmax: 6, ymin: 0, ymax: 4 } });
    assert.match(out, /xmin=-2, xmax=6, ymin=0, ymax=4,/);
  });

  test('an empty source still gives a compilable document', () => {
    const out = tex('');
    assert.match(out, /% nothing in the source draws/);
    assert.match(out, /\\end\{document\}/);
  });

  test('the title goes into the leading comment', () => {
    assert.match(tex('point p = (0,0)', { title: 'orbit.dsmx' }), /^% generated by desmos-ide from orbit\.dsmx/);
  });
});

describe('colors', () => {
  test('a named color becomes a definecolor', () => {
    const out = tex('point p = (1, 2) as { color: red }');
    assert.match(out, /\\definecolor\{dslc1\}\{HTML\}\{C74440\}/);
  });

  test('one definition per distinct color', () => {
    const out = tex('point a = (0,0) as { color: red }\npoint b = (1,1) as { color: red }');
    assert.equal(out.split('\\definecolor').length - 1, 1);
  });
});

describe('declared values become macros', () => {
  test('a constant is a macro, not a plot', () => {
    const out = tex('a = 3\ny = a*x');
    assert.match(out, /\\pgfmathsetmacro\{\\dsla\}\{3\}/);
    assert.match(out, /\\addplot\[[^\]]*\] \{\(\\dsla\*x\)\};/);
  });

  test('a slider keeps its initial value', () => {
    assert.match(tex('a = slider(2, 0, 10)'), /\\pgfmathsetmacro\{\\dsla\}\{2\}/);
  });

  test('the clock keeps its start', () => {
    assert.match(tex('time T = time(0..10)'), /\\pgfmathsetmacro\{\\dslT\}\{0\}/);
  });

  test('two names that share letters get different macros', () => {
    const out = tex('a1 = 1\na2 = 2');
    assert.match(out, /\\pgfmathsetmacro\{\\dsla\}\{1\}/);
    assert.match(out, /\\pgfmathsetmacro\{\\dslax\}\{2\}/);
  });
});

describe('trigonometry crosses into degrees', () => {
  test('sin of a radian argument is wrapped in deg', () => {
    assert.match(tex('y = sin(x)'), /\{sin\(deg\(x\)\)\}/);
  });

  test('arcsin comes back as radians', () => {
    assert.match(tex('y = arcsin(x)'), /\{rad\(asin\(x\)\)\}/);
  });

  test('log is base ten, the way desmos means it', () => {
    assert.match(tex('y = log(x)'), /\{log10\(x\)\}/);
  });
});

describe('statements that draw', () => {
  test('a point is a mark and a label', () => {
    const out = plots('point p = (1, 2)');
    assert.match(out[0], /only marks, mark=\*/);
    assert.match(out[0], /coordinates \{\(1,2\)\}/);
    assert.match(out[1], /\\node\[.*\] at \(axis cs:1,2\) \{\$p\$\}/);
  });

  test('a circle is a parametric sweep in degrees', () => {
    const out = plots('circle c = circle(center=(1, 2), radius=3)')[0];
    assert.match(out, /domain=0:360, variable=\\t/);
    assert.match(out, /\(\{1\+3\*cos\(\\t\)\}, \{2\+3\*sin\(\\t\)\}\)/);
  });

  test('a slope-intercept line needs two samples', () => {
    const out = plots('line l = line(slope=2, intercept=1)')[0];
    assert.match(out, /samples=2/);
    assert.match(out, /\{2\*x\+1\}/);
  });

  test('a standard-form line is solved for y', () => {
    assert.match(plots('line l = 2*x + y == 4')[0], /\{-2\*x\+4\}/);
  });

  test('a vertical line becomes a pair of coordinates', () => {
    assert.match(plots('line l = 2*x == 4')[0], /coordinates \{\(2,-10\) \(2,10\)\}/);
  });

  test('a parametric curve binds its variable to \\t', () => {
    const out = plots('curve ring = curve(t -> (cos(t), sin(t)), 0..6.28)')[0];
    assert.match(out, /domain=0:6.28, variable=\\t/);
    assert.match(out, /\(\{cos\(deg\(\\t\)\)\}, \{sin\(deg\(\\t\)\)\}\)/);
  });

  test('the inline `for` form is the same sweep as `curve`', () => {
    const inline = plots('pts = [(cos(t), sin(t)) for t in 0..6.28]');
    assert.deepEqual(inline, plots('curve pts = curve(t -> (cos(t), sin(t)), 0..6.28)'));
    assert.match(inline[0], /variable=\\t/);
  });

  test('a tuple variable is drawn as a point', () => {
    assert.match(plots('p = (1, 2)')[0], /only marks.*coordinates \{\(1,2\)\}/);
  });

  test('a curve step sets the sample count', () => {
    assert.match(plots('curve c = curve(t -> (t, t), 0..10 step 2)')[0], /samples=6/);
  });

  test('a polygon closes back onto its first vertex', () => {
    assert.match(
      plots('polygon tri = polygon([(0,0), (1,0), (0,1)])')[0],
      /coordinates \{\(0,0\) \(1,0\) \(0,1\) \(0,0\)\}/,
    );
  });

  test('a segment is two coordinates and no marks', () => {
    assert.match(plots('segment s = segment((0,0), (1,1))')[0], /no marks\] coordinates \{\(0,0\) \(1,1\)\}/);
  });

  test('a grid draws one line per integer', () => {
    const out = plots('grid g = grid(2, 2)');
    assert.equal(out.length, 6);
  });

  test('a wave follows the codegen formula', () => {
    const out = plots('wave w = wave(freq=2, amp=1)')[0];
    assert.match(out, /\(\{\\t\+0\}, \{1\*sin\(deg\(2\*\\t\+0\)\)\+0\}\)/);
  });

  test('a spiral sweeps its turns', () => {
    assert.match(plots('spiral s = spiral(turns=2, spacing=0.2)')[0], /domain=0:12.56637061/);
  });

  test('a where clause narrows the plot', () => {
    assert.match(plots('y = x^2 where x > 2')[0], /domain=2:10/);
  });
});

describe('text', () => {
  test('latex specials in a label are escaped', () => {
    assert.match(plots('text l = text("50% & more_x", at=(0, 0))')[0], /\{50\\% \\& more\\_x\}/);
  });
});

describe('what pgfplots cannot say is reported, not guessed', () => {
  test('a region is left out', () => {
    const out = skipped('region r = y > x^2');
    assert.equal(out.length, 1);
    assert.equal(out[0].name, 'r');
    assert.match(out[0].reason, /inequality region/);
  });

  test('a piecewise without an else branch is left out', () => {
    assert.equal(skipped('y = { x > 0: x^2, x < 0: -x }').length, 1);
  });

  test('a piecewise with an else branch becomes a ternary', () => {
    assert.equal(skipped('y = { x > 0: x^2, else: 0 }').length, 0);
    assert.match(plots('y = { x > 0: x^2, else: 0 }')[0], /\?.*:/);
  });

  test('a named definition draws nothing and is not reported as a loss', () => {
    // desmos does not draw `a = x^2` either, so leaving it out costs nothing
    assert.deepEqual(skipped('a = x^2'), []);
    assert.deepEqual(plots('a = x^2'), []);
  });

  test('a non-constant point is reported', () => {
    const out = skipped('a = slider(1, 0, 5)\npoint p = (a, 2)');
    assert.equal(out.length, 0, 'a slider folds to its initial value');
  });

  test('a compile error passes straight through', () => {
    const r = compileToTex('point p = (nope, 2)');
    assert.equal(r.success, false);
  });
});
