// compiles the swift dialog helpers and the quick look extension ahead of the bundle

import { execFile } from 'child_process';
import { promisify } from 'util';
import { mkdir, readdir, rm, writeFile } from 'fs/promises';
import { join } from 'path';
import { KEYWORDS } from '../src/compiler/lexer';
import { BUILTIN_NAMES, STYLE_FNS } from '../src/compiler/builtins';
import pkg from '../package.json';

const execFileAsync = promisify(execFile);

const ROOT = join(import.meta.dir, '..');
const SOURCE_DIR = join(ROOT, 'bun', 'native');
const QUICKLOOK_DIR = join(SOURCE_DIR, 'quicklook');
const OUT_DIR = join(ROOT, 'dist', 'native');
// the extension is not copied into the bundle by electrobun, it is installed into
// Contents/PlugIns by scripts/release.sh, so it is built outside dist/native
const QL_OUT_DIR = join(ROOT, 'dist', 'quicklook');
const APPEX = join(QL_OUT_DIR, 'DsmxQuickLook.appex');

if (process.platform !== 'darwin') {
  console.log('build-native: not macOS, nothing to compile');
  process.exit(0);
}

await mkdir(OUT_DIR, { recursive: true });

// --- the dialog helpers, one binary each -----------------------------------

const sources = (await readdir(SOURCE_DIR, { withFileTypes: true }))
  .filter(e => e.isFile() && e.name.endsWith('.swift'))
  .map(e => e.name);

if (sources.length === 0) {
  console.error(`build-native: no .swift files in ${SOURCE_DIR}`);
  process.exit(1);
}

for (const file of sources) {
  const name = file.replace(/\.swift$/, '');
  await execFileAsync('swiftc', ['-O', join(SOURCE_DIR, file), '-o', join(OUT_DIR, name)]);
  console.log(`build-native: ${name}`);
}

// --- the quick look extension ----------------------------------------------

// the preview colours the same words the editor does, so its tables come from the
// compiler tables and are never edited by hand
const swiftSet = (names: readonly string[]) =>
  `[\n${[...names].map(n => `  ${JSON.stringify(n)},`).join('\n')}\n]`;

const tables = `// generated by scripts/build-native.ts — do not edit

let KEYWORDS: Set<String> = ${swiftSet([...KEYWORDS])}

let BUILTINS: Set<String> = ${swiftSet([...BUILTIN_NAMES, ...STYLE_FNS.map(f => f.name)])}
`;

const GEN_DIR = join(QL_OUT_DIR, '.gen');
await mkdir(GEN_DIR, { recursive: true });
await writeFile(join(GEN_DIR, 'Tables.swift'), tables);

const qlSources = (await readdir(QUICKLOOK_DIR))
  .filter(f => f.endsWith('.swift'))
  .map(f => join(QUICKLOOK_DIR, f));

await rm(APPEX, { recursive: true, force: true });
await mkdir(join(APPEX, 'Contents', 'MacOS'), { recursive: true });

await execFileAsync('swiftc', [
  '-O',
  '-parse-as-library',
  '-module-name', 'DsmxQuickLook',
  '-target', `${process.arch === 'arm64' ? 'arm64' : 'x86_64'}-apple-macos12.0`,
  '-framework', 'QuickLookUI',
  // an app extension is entered through NSExtensionMain, not main()
  '-Xlinker', '-e', '-Xlinker', '_NSExtensionMain',
  ...qlSources,
  join(GEN_DIR, 'Tables.swift'),
  '-o', join(APPEX, 'Contents', 'MacOS', 'DsmxQuickLook'),
]);

const plist = (await Bun.file(join(QUICKLOOK_DIR, 'Info.plist')).text())
  .replaceAll('__VERSION__', pkg.version);
await writeFile(join(APPEX, 'Contents', 'Info.plist'), plist);

console.log('build-native: DsmxQuickLook.appex');
