// compiles the swift dialog helpers and the quick look extension ahead of the bundle

import { execFile } from 'child_process';
import { promisify } from 'util';
import { mkdir, readdir, readFile, rm, writeFile } from 'fs/promises';
import { existsSync } from 'fs';
import { createHash } from 'crypto';
import { join } from 'path';
import { KEYWORDS } from '../src/compiler/lexer';
import { BUILTIN_NAMES, STYLE_FNS } from '../src/compiler/builtins';
import pkg from '../package.json';

const execFileAsync = promisify(execFile);

const ROOT = join(import.meta.dir, '..');
const SOURCE_DIR = join(ROOT, 'bun', 'native');
const QUICKLOOK_DIR = join(SOURCE_DIR, 'quicklook');
const OUT_DIR = join(ROOT, 'dist', 'native');
const QL_OUT_DIR = join(ROOT, 'dist', 'quicklook');
const APPEX = join(QL_OUT_DIR, 'DsmxQuickLook.appex');

if (process.platform !== 'darwin') {
  console.log('build-native: not macOS, nothing to compile');
  process.exit(0);
}

await mkdir(OUT_DIR, { recursive: true });

// staleness

// if compile if unchanged
const { stdout: swiftVersion } = await execFileAsync('swiftc', ['--version']);

// the helpers are universal, so one machine builds what either arch release needs
const ARCHES = ['arm64', 'x86_64'];
const DEPLOYMENT = '14.0';

const hashOf = (parts: string[]): string => {
  const h = createHash('sha256').update(swiftVersion).update(ARCHES.join()).update(DEPLOYMENT);
  for (const p of parts) h.update(p);
  return h.digest('hex');
};

const upToDate = async (stamp: string, hash: string, outputs: string[]): Promise<boolean> => {
  if (!outputs.every(o => existsSync(o))) return false;
  return (await readFile(stamp, 'utf8').catch(() => '')) === hash;
};

const universal = async (args: string[], out: string): Promise<void> => {
  const slices: string[] = [];
  for (const arch of ARCHES) {
    const slice = `${out}.${arch}`;
    await execFileAsync('swiftc', ['-target', `${arch}-apple-macos${DEPLOYMENT}`, ...args, '-o', slice]);
    slices.push(slice);
  }
  await execFileAsync('lipo', ['-create', ...slices, '-output', out]);
  await Promise.all(slices.map(s => rm(s, { force: true })));
};

// dialog helpers

const sources = (await readdir(SOURCE_DIR, { withFileTypes: true }))
  .filter(e => e.isFile() && e.name.endsWith('.swift'))
  .map(e => e.name);

if (sources.length === 0) {
  console.error(`build-native: no .swift files in ${SOURCE_DIR}`);
  process.exit(1);
}

for (const file of sources) {
  const name = file.replace(/\.swift$/, '');
  const out = join(OUT_DIR, name);
  const stamp = join(OUT_DIR, `.${name}.stamp`);
  const hash = hashOf([await readFile(join(SOURCE_DIR, file), 'utf8')]);

  if (await upToDate(stamp, hash, [out])) {
    console.log(`build-native: ${name} is up to date`);
    continue;
  }

  await universal(['-O', join(SOURCE_DIR, file)], out);
  await writeFile(stamp, hash);
  console.log(`build-native: ${name}`);
}

// quick look ext
const swiftSet = (names: readonly string[]) =>
  `[\n${[...names].map(n => `  ${JSON.stringify(n)},`).join('\n')}\n]`;

const tables = `// generated by scripts/build-native.ts — do not edit

let KEYWORDS: Set<String> = ${swiftSet([...KEYWORDS])}

let BUILTINS: Set<String> = ${swiftSet([...BUILTIN_NAMES, ...STYLE_FNS.map(f => f.name)])}
`;

const qlSources = (await readdir(QUICKLOOK_DIR))
  .filter(f => f.endsWith('.swift'))
  .map(f => join(QUICKLOOK_DIR, f));

const plistTemplate = await readFile(join(QUICKLOOK_DIR, 'Info.plist'), 'utf8');
const qlBinary = join(APPEX, 'Contents', 'MacOS', 'DsmxQuickLook');
const qlPlist = join(APPEX, 'Contents', 'Info.plist');
const qlStamp = join(QL_OUT_DIR, '.appex.stamp');
const qlHash = hashOf([
  tables,
  ...(await Promise.all(qlSources.map(f => readFile(f, 'utf8')))),
  plistTemplate,
  pkg.version,
]);

if (await upToDate(qlStamp, qlHash, [qlBinary, qlPlist])) {
  console.log('build-native: DsmxQuickLook.appex is up to date');
} else {
  const GEN_DIR = join(QL_OUT_DIR, '.gen');
  await mkdir(GEN_DIR, { recursive: true });
  await writeFile(join(GEN_DIR, 'Tables.swift'), tables);

  await rm(APPEX, { recursive: true, force: true });
  await mkdir(join(APPEX, 'Contents', 'MacOS'), { recursive: true });

  await universal([
    '-O',
    '-parse-as-library',
    '-module-name', 'DsmxQuickLook',
    '-framework', 'QuickLookUI',
    '-Xlinker', '-e', '-Xlinker', '_NSExtensionMain',
    ...qlSources,
    join(GEN_DIR, 'Tables.swift'),
  ], qlBinary);

  await writeFile(qlPlist, plistTemplate.replaceAll('__VERSION__', pkg.version));
  await writeFile(qlStamp, qlHash);
  console.log('build-native: DsmxQuickLook.appex');
}
